### ISSUE TITLE
Regarding Projects

### ISSUE THREAD

**Issue by rhnvrm** [code-together/mentorship#16]
We could include a reference to https://github.com/karan/Projects and/or work on those projects with mentees so that the people who complete the projects can send pull requests to https://github.com/karan/Projects-Solutions

**Comment by avinassh** [comment]
Sure, I will do it in sometime.  Thanks!

**Comment by rhnvrm** [comment]
I was experimenting with submodules on my fork, but I dont know if that is the way we should go about it. https://github.com/rhnvrm/mentorship/tree/c342d9549289b75c9dc0c90ff02c3ce765b78eaf

What do you think?
