### ISSUE TITLE
Using gitter.im 

### ISSUE THREAD

**Issue by rhnvrm** [code-together/mentorship#18]
Another enhancement to the repo could be to use http://gitter.im as a chat platform for the repository as many people who visit the repo might not be joining the slack chat room. It has features for private chat also. I would have sent a PR for this but it can only be done by the owners of the repo. It also has a simple badge which can be added to the Readme.

**Comment by avinassh** [comment]
Hey, we will stick with Slack.

Many people are already on Slack channel and it is not only for mentorship, but it has other regular members of Hacker Threads also. At this point, I don't see why we should move away from Slack.

PS: I am biased because I personally like Slack more than Gitter.
